			
		</div>
	</div>
	
	<footer>
		<div class="container">
			<div class="row text-center white">
			<p>Copyright © <?php echo date("Y"); ?> López Padilla. Todos los derechos reservados. | <a href="#" class="white" data-toggle="modal" data-target="#myModal">Aviso de privacidad</a></p>
			</div>
		</div>
	</footer>
	
	<?php include 'modal.inc'; ?>

	<script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
	<script src="assets/js/idangerous.swiper.min.js"></script>
	<script src="assets/js/jquery.viewportchecker.js"></script>
	<script src="assets/js/jquery.scrollUp.min.js"></script>		
	<script src="assets/js/isotope.pkgd.min.js"></script>
	<script src="assets/js/jquery.circliful.min.js"></script>		
	<script src="assets/js/global.js"></script>	
  </body>
</html>